### ISSUE TITLE
Missing Method

### ISSUE THREAD

**Issue by Sarahlls** [Nova791/SOD_DensityMod#3]
Heya friend, I noticed today that I'm getting a missing method error in my bepinex terminal from your mod. I pasted the error message below but it looks like either "Void PopupMessageController.popupmessage is either no longer a valid method, or it's name changed.

> [Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void PopupMessageController.PopupMessage(System.String, Boolean, Boolean, System.String, System.String, Boolean, AffectPauseState, Boolean, System.String, Boolean, Boolean, Boolean, Boolean, System.String, System.String, Boolean, System.String, Boolean, System.String, System.String)'.
   at DensityMod.AnyCitySizeHooks.MainMenuController_Start.<>c__DisplayClass5_0.<Postfix>b__0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )

It's constantly throwing this errors and causing lot's of stutter.

**Comment by Nova791** [comment]
This was an issue of the mod not being built for the most recent experimentation. This issue should now be resolved. Closing
