### ISSUE TITLE
Stuck in loading screen when generating new city. 

### ISSUE THREAD

**Issue by Banzaiburger** [Nova791/SOD_DensityMod#4]
When attempting to create a new city with this mod enabled, the loading proces sticks on "Creating Citizens." The error message " [Error  :     Unity] NullReferenceException: Object reference not set to an instance of an object" appears in the command prompt generated by beplinexpack. No mods other than beplinexpack were enabled. This happens when attempting to generate a city at any size.

**Comment by Banzaiburger** [comment]
Actually, this seems to be happening even if I am not running any mods, so it probably isn't this mod that is the issue. Appologies for jumping to conclusions!

**Comment by Nova791** [comment]
No worries! Closing the issue then
